package quote 

type AutoGenerated struct {
	Finance struct {
		Result struct {
			Symbol         string `json:"symbol"`
			InstrumentInfo struct {
				TechnicalEvents struct {
					Provider  string `json:"provider"`
					ShortTerm string `json:"shortTerm"`
					MidTerm   string `json:"midTerm"`
					LongTerm  string `json:"longTerm"`
				} `json:"technicalEvents"`
				KeyTechnicals struct {
					Provider   string  `json:"provider"`
					Resistance float64 `json:"resistance"`
					StopLoss   float64 `json:"stopLoss"`
				} `json:"keyTechnicals"`
				Valuation struct {
					Color         int    `json:"color"`
					Description   string `json:"description"`
					RelativeValue string `json:"relativeValue"`
					Provider      string `json:"provider"`
				} `json:"valuation"`
			} `json:"instrumentInfo"`
			Reports         []interface{} `json:"reports"`
			CompanySnapshot struct {
				SectorInfo string `json:"sectorInfo"`
				Company    struct {
					InsiderSentiments float64 `json:"insiderSentiments"`
					EarningsReports   float64 `json:"earningsReports"`
				} `json:"company"`
				Sector struct {
					Innovativeness    float64 `json:"innovativeness"`
					Hiring            float64 `json:"hiring"`
					Sustainability    float64 `json:"sustainability"`
					InsiderSentiments float64 `json:"insiderSentiments"`
					EarningsReports   float64 `json:"earningsReports"`
					Dividends         float64 `json:"dividends"`
				} `json:"sector"`
			} `json:"companySnapshot"`
		} `json:"result"`
		Error interface{} `json:"error"`
	} `json:"finance"`
}
